AWSTemplateFormatVersion: '2010-09-09'
Description: create an IAM Role

Resources:
  EC2S3AccessRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: EC2S3AccessRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - PolicyName: policy-930am-batch
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - ec2:Describe*
                  - s3:PutObject
                Resource: "*"
