AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: My-Admin-PB
      Description: PB
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:StartInstances
              - ec2:StopInstances
              - s3:ListBucket
              - s3:PutObject
              - s3:GetObject
            Resource: "*"
