AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: devops-user

  MyUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3-inline-policy
      Users:
        - !Ref MyIAMUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource: "*"
